#!/bin/bash
set -e     # to avoid errors being silently ignored

# Installation du kernel Bash dans l'environnement Jupyter
python -m bash_kernel.install --sys-prefix

# Adding the notebook environment's bin directory to PATH.
export PATH=/srv/conda/envs/notebook/bin:$PATH

# Enregistre le kernel R pour cet environnement
R --quiet -e "IRkernel::installspec(prefix='/srv/conda/envs/notebook')" || true

# Install R packages
# if not available as conda package
# R -e "install.packages('diagram', repos='http://cran.rstudio.com/')"

# Install R/Bioconductor package
# if not available as conda package

# First install Bioconductor package manager
# https://bioconductor.org/install/
# R -e "install.packages('BiocManager', repos='http://cran.rstudio.com/')"
# R -e "BiocManager::install()"

# Then install required packages
# Biostrings: Efficient manipulation of biological strings
# https://bioconductor.org/packages/release/bioc/html/Biostrings.html
# R -e "BiocManager::install('Biostrings')"
